### ISSUE TITLE
Format the countdown

### ISSUE THREAD

**Issue by BhavyaCodes** [Juggernaut9/itsalmost-clone-client#13]
Format the timer to look like this
![image](https://user-images.githubusercontent.com/58269749/100379905-c0c0da00-303b-11eb-9e4e-feca983dc161.png)
Currently it looks like this
![image](https://user-images.githubusercontent.com/58269749/100380237-77bd5580-303c-11eb-8643-5e702c176b56.png)

Also the times shouldn't show 0 years, 0 months, 0 hours etc, Don't necessarily need to style it, only format the strings

**Comment by BhavyaCodes** [comment]
please check the live example, also try to format ms to always display 3 characters, example 1 ms should be formatted to `001`

**Comment by matthewfee** [comment]
I'm working on this.

**Comment by BhavyaCodes** [comment]
Fixed with PR #16
