### ISSUE TITLE
display another message instead of negative countdown

### ISSUE THREAD

**Issue by BhavyaCodes** [Juggernaut9/itsalmost-clone-client#14]
![image](https://user-images.githubusercontent.com/58269749/100380615-2eb9d100-303d-11eb-9ac8-97fad90741d5.png)

You can be creative with the message, or just make it generic

**Comment by saiviswateja** [comment]
I think I can work on this

**Comment by BhavyaCodes** [comment]
Assigned, Go ahead 😀

**Comment by BhavyaCodes** [comment]
Fixed with PR #15
