### ISSUE TITLE
Add Date and time picker to Landing.js component

### ISSUE THREAD

**Issue by BhavyaCodes** [Juggernaut9/itsalmost-clone-client#6]
take input using the date and time picker and send the selected input to in post request for creating event. Use external libraries to make your life easier. 

https://projects.wojtekmaj.pl/react-datetime-picker/

You may use other libraries too, this is just 1 example

**Comment by bryanurizar** [comment]
Hey can I give this one a go?

**Comment by BhavyaCodes** [comment]
Assigned 😁
